// LOCALHOST
###
GET http://localhost:8080/pilots
###

### Get Pilot by ID. 
GET http://localhost:8080/pilots/664febe76317b3b4fde53ce4

### Create pilot
POST http://localhost:8080/pilots HTTP/1.1
content-type: application/json

{
        "firstName": "Andres ",
        "lastName": "Hoeger",
        "networkID": "1222330",
        "flights": "3717",
        "pilotID": "DVA11156"
}
### PUT pilot
PUT http://localhost:8080/pilots/6657fde23161a6fc6419a6cc HTTP/1.1
content-type: application/json

{
        "firstName": "Andres ",
        "lastName": "Honegger",
        "networkID": "1222330",
        "flights": "3717",
        "pilotID": "DVA11156"
}

### DELETE Pilot
DELETE http://localhost:8080/pilots/6657f9ac5b2d8400508ea3d8

{
        "firstName": "Andres ",
        "lastName": "Honegger",
        "networkID": "1222330",
        "flights": "3717",
        "pilotID": "DVA11156"
}





// PRODUCTION Deploy

### Get all pilots on production
GET https://dva-project.onrender.com/pilots HTTP/1.1

### Get pilot by id
GET https://dva-project.onrender.com/pilots/664febe76317b3b4fde53ce4 HTTP/1.1


### Create pilots on production
POST https://dva-project.onrender.com/pilots HTTP/1.1
content-type: application/json

{
        "firstName": "Jim",
        "lastName": "Warner",
        "networkID": "938171",
        "flights": "1762",
        "pilotID": "DVA2533"
}


### PUT contact on production
PUT https://dva-project.onrender.com/pilots HTTP/1.1
content-type: application/json

{
        "firstName": "Scott ",
        "lastName": "Williams",
        "networkID": "980239",
        "flights": "6704",
        "pilotID": "DVA4176"
}

### DELETE contact on production
DELETE https://dva-project.onrender.com/pilots HTTP/1.1