// LOCALHOST
###
GET http://localhost:8080/
###

### Create contact
POST http://localhost:8080/pilots HTTP/1.1
content-type: application/json

{
        "firstName": "Salem ",
        "lastName": "Gbian",
        "networkID": "1096218",
        "flights": "1552",
        "pilotID": "DVA7758"
}








// PRODUCTION Deploy

### Get all contacts on production
GET https://dva-project.onrender.com/pilots HTTP/1.1


### Create contact on production
POST https://dva-project.onrender.com/pilots HTTP/1.1
content-type: application/json

{
        "firstName": "Ken ",
        "lastName": "Webber",
        "networkID": "1333821",
        "flights": "332",
        "pilotID": "DVA12746"
}


