// LOCALHOST
###
GET http://localhost:8080/
###

### Create contact
POST http://localhost:8080/pilots HTTP/1.1
content-type: application/json

{
        "firstName": "Andres ",
        "lastName": "Honegger",
        "networkID": "1222330",
        "flights": "3717",
        "pilotID": "DVA11156"
}








// PRODUCTION Deploy

### Get all contacts on production
GET https://dva-project.onrender.com/pilots HTTP/1.1


### Create contact on production
POST https://dva-project.onrender.com/pilots HTTP/1.1
content-type: application/json

{
        "firstName": "Scott ",
        "lastName": "Williams",
        "networkID": "980239",
        "flights": "6704",
        "pilotID": "DVA4176"
}


